# These are supported funding model platforms

github: mohdumarbutt
buy_me_a_coffee: ['buymeacoffee.com/umarbutt']
custom: ['https://www.linkedin.com/in/mohdumarbutt', 'https://instagram.com/theumar_butt']
